### PR TITLE
NCS functions

### PR DESCRIPTION
**Pull request by nytamin**
This PR aims to add NCS-functions so that mos-connection can be used by an NCS, not just a mos-device.

_work-in-progress_

### CODE REVIEW

**Comment by eborned** [comment]
We are currently experimenting with this connector and the NCS feature is something we would like to use, test and expand on. I noticed that the `roListAll` isn't currently implemented. Are there any specific issues we can work on? Or is this PR obsolete?

**Comment by nytamin** [comment]
The work on this PR was paused a while ago due to other focuses in the team.
I did find a few uncommitted things locally however now when I dusted it off. I'll see if I can push them tonight and I'll be able to give you a better reply tomorrow on forward directions.

Contributions are always welcome and I can provide guidance and do code reviews during implementations.

**Comment by eborned** [comment]
Great, sounds good. We are testing out the connection library to connect our Newsroom system to MOS devices, so you can expect some new features and/or bug fixes in the near future.

**Comment by nytamin** [comment]
Most (all?) of the NCS functions for profiles 0,1,2,3 & 4 have been implemented (although some tests are lacking still).
I've found a few issues (unrelated to this PR) here and there in the backend side of things, but that'll have to be addressed later, I think.
This PR has gone on long enough by now, so I'm going ahead to merge it.

**Pull request merged**
