### PR TITLE
Fix xml2ObjPaths for a xml of one flat path object.

### PR DESCRIPTION
**Pull request by Wallacy**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix.

* **What is the current behavior?** (You can also link to an open issue here)

Hello, i run in this corner case testing this lib over one NCS system.

The xml2ObjPaths argument sometimes receive a flat objPath object instead a object with a objPath and them the info.

Like this: 
```
{
text: "\\Videos\1080p\Wonderful Universe - Part 2 FULL H…",
objPath: "\\Videos\1080p\Wonderful Universe - Part 2 FULL H…",
techDescription: "VIDEO"
}
```
instead this:

```
{
"objPath":{
   "$name":"objPath",
   "$type":"text",
   "text":"\\Videos\1080p\Wonderful Universe - Part 2 FULL H…",
   "techDescription":"VIDEO"
  }
}"
```

This only occurs when the MOS xml has only one _objPath_ inside of a _objPaths_.

* **What is the new behavior (if this is a feature change)?**

Will thread this corner case. To solve this I'm looking of 'techDescription' property because is a required one, and in a not top level property on the regular scenario.

### CODE REVIEW

**Comment by nytamin** [comment]
Thanks for this PR!
Before I merge it, could you provide an example of the input-xml that causes this error? This seems like a perfect example of something we _should_ have caught in the unit tests. :)

Speaking of tests, there are some issues with failing unit tests that need to be resolved before I can merge. Please run `yarn test` to see what needs to be fixed.

**Comment by Wallacy** [comment]
Sorry about the test, my mistake.

I push the fix. But didn't include the test scenario for the original fix on the jest case. I will provide here the example and you can include if want.

Basically this two cases:

```
<objPaths>
		<objPath techDescription="VIDEO">http://media.example.com.br:9000/mamfolders/Original/3afb7390-7f0c-4d52-ab74-159fad1df7ba.mp4</objPath>
		<objProxyPath techDescription="JPG">http://media.example.com.br:9000/mamfolders/Proxy/3afb7390-7f0c-4d52-ab74-159fad1df7ba_0.jpg</objProxyPath>
		<objProxyPath techDescription="VIDEO">http://media.example.com.br:9000/mamfolders/Proxy/3afb7390-7f0c-4d52-ab74-159fad1df7ba_1.mp4</objProxyPath>
</objPaths>
```
```
<objPaths>
       <objPath techDescription="">D:\Videos\1080p\Wonderful Universe - Part 2 FULL HD.mp4</objPath>
</objPaths>
```

Full:

```
<mos>
	<mosID>mediaserver.example.tv</mosID>
	<ncsID>ncs.example.tv</ncsID>
	<messageID>20</messageID>
	<roList>
		<roID>R_131</roID>
		<roSlug>Fato News 2019-01-31</roSlug>
		<roChannel></roChannel>
		<roEdStart>2019-01-31T12:30:00,000</roEdStart>
		<roEdDur>00:30:00</roEdDur>
		<roTrigger></roTrigger>
		<macroIn></macroIn>
		<macroOut></macroOut>
		<mosExternalMetadata>
			<mosScope>PLAYLIST</mosScope>
			<mosSchema></mosSchema>
			<mosPayload>
				<ready>false</ready>
			</mosPayload>
		</mosExternalMetadata>
		<story>
			<storyID>1203</storyID>
			<storySlug></storySlug>
			<storyNum>05</storyNum>
			<mosExternalMetadata>
				<mosScope>PLAYLIST</mosScope>
				<mosSchema></mosSchema>
				<mosPayload>
					<block>0</block>
					<type />
				</mosPayload>
			</mosExternalMetadata>
			<item>
				<itemID>V_700</itemID>
				<itemSlug>AVID MEDIA CENTRAL</itemSlug>
				<objID>3afb7390-7f0c-4d52-ab74-159fad1df7ba</objID>
				<mosID>mam</mosID>
				<mosAbstract></mosAbstract>
				<objPaths>
					<objPath techDescription="VIDEO">http://media.example.com.br:9000/mamfolders/Original/3afb7390-7f0c-4d52-ab74-159fad1df7ba.mp4</objPath>
					<objProxyPath techDescription="JPG">http://media.example.com.br:9000/mamfolders/Proxy/3afb7390-7f0c-4d52-ab74-159fad1df7ba_0.jpg</objProxyPath>
					<objProxyPath techDescription="VIDEO">http://media.example.com.br:9000/mamfolders/Proxy/3afb7390-7f0c-4d52-ab74-159fad1df7ba_1.mp4</objProxyPath>
				</objPaths>
				<itemChannel></itemChannel>
				<itemEdStart></itemEdStart>
				<itemEdDur>49550</itemEdDur>
				<itemUserTimingDur></itemUserTimingDur>
				<itemTrigger>MANUAL</itemTrigger>
				<macroIn></macroIn>
				<macroOut></macroOut>
			</item>
		</story>
		<story>
			<storyID>1204</storyID>
			<storySlug></storySlug>
			<storyNum>06</storyNum>
			<mosExternalMetadata>
				<mosScope>PLAYLIST</mosScope>
				<mosSchema></mosSchema>
				<mosPayload>
					<block>0</block>
					<type />
				</mosPayload>
			</mosExternalMetadata>
			<item>
				<itemID>V_703</itemID>
				<itemSlug>Wonderful Universe - Part 2 FULL HD.mp4</itemSlug>
				<objID>44AA504C6ECC428E94A44E9A87C3294D4709B442B62C7E5316D333BFFFCE748A</objID>
				<mosID>w.example.tv</mosID>
				<mosAbstract></mosAbstract>
				<objPaths>
					<objPath techDescription="">D:\Videos\1080p\Wonderful Universe - Part 2 FULL HD.mp4</objPath>
				</objPaths>
				<itemChannel></itemChannel>
				<itemEdStart></itemEdStart>
				<itemEdDur>239700</itemEdDur>
				<itemUserTimingDur></itemUserTimingDur>
				<itemTrigger>MANUAL</itemTrigger>
				<macroIn></macroIn>
				<macroOut></macroOut>
			</item>
		</story>
	</roList>
</mos>
<mos>
	<mosID>mediaserver.example.tv</mosID>
	<ncsID>ncs.example.tv</ncsID>
	<messageID>20</messageID>
	<roList>
		<roID>R_131</roID>
		<roSlug>Fato News 2019-01-31</roSlug>
		<roChannel></roChannel>
		<roEdStart>2019-01-31T12:30:00,000</roEdStart>
		<roEdDur>00:30:00</roEdDur>
		<roTrigger></roTrigger>
		<macroIn></macroIn>
		<macroOut></macroOut>
		<mosExternalMetadata>
			<mosScope>PLAYLIST</mosScope>
			<mosSchema></mosSchema>
			<mosPayload>
				<ready>false</ready>
			</mosPayload>
		</mosExternalMetadata>
		<story>
			<storyID>1203</storyID>
			<storySlug></storySlug>
			<storyNum>05</storyNum>
			<mosExternalMetadata>
				<mosScope>PLAYLIST</mosScope>
				<mosSchema></mosSchema>
				<mosPayload>
					<block>0</block>
					<type />
				</mosPayload>
			</mosExternalMetadata>
			<item>
				<itemID>V_700</itemID>
				<itemSlug>AVID MEDIA CENTRAL</itemSlug>
				<objID>3afb7390-7f0c-4d52-ab74-159fad1df7ba</objID>
				<mosID>mam</mosID>
				<mosAbstract></mosAbstract>
				<objPaths>
					<objPath techDescription="VIDEO">http://media.example.com.br:9000/mamfolders/Original/3afb7390-7f0c-4d52-ab74-159fad1df7ba.mp4</objPath>
					<objProxyPath techDescription="JPG">http://media.example.com.br:9000/mamfolders/Proxy/3afb7390-7f0c-4d52-ab74-159fad1df7ba_0.jpg</objProxyPath>
					<objProxyPath techDescription="VIDEO">http://media.example.com.br:9000/mamfolders/Proxy/3afb7390-7f0c-4d52-ab74-159fad1df7ba_1.mp4</objProxyPath>
				</objPaths>
				<itemChannel></itemChannel>
				<itemEdStart></itemEdStart>
				<itemEdDur>49550</itemEdDur>
				<itemUserTimingDur></itemUserTimingDur>
				<itemTrigger>MANUAL</itemTrigger>
				<macroIn></macroIn>
				<macroOut></macroOut>
			</item>
		</story>
		<story>
			<storyID>1204</storyID>
			<storySlug></storySlug>
			<storyNum>06</storyNum>
			<mosExternalMetadata>
				<mosScope>PLAYLIST</mosScope>
				<mosSchema></mosSchema>
				<mosPayload>
					<block>0</block>
					<type />
				</mosPayload>
			</mosExternalMetadata>
			<item>
				<itemID>V_703</itemID>
				<itemSlug>Wonderful Universe - Part 2 FULL HD.mp4</itemSlug>
				<objID>44AA504C6ECC428E94A44E9A87C3294D4709B442B62C7E5316D333BFFFCE748A</objID>
				<mosID>w.example.tv</mosID>
				<mosAbstract></mosAbstract>
				<objPaths>
					<objPath techDescription="">D:\Videos\1080p\Wonderful Universe - Part 2 FULL HD.mp4</objPath>
				</objPaths>
				<itemChannel></itemChannel>
				<itemEdStart></itemEdStart>
				<itemEdDur>239700</itemEdDur>
				<itemUserTimingDur></itemUserTimingDur>
				<itemTrigger>MANUAL</itemTrigger>
				<macroIn></macroIn>
				<macroOut></macroOut>
			</item>
		</story>
	</roList>
</mos>
```

**Comment by Wallacy** [comment]
Did you need any more info?

**Comment by nytamin** [comment]
Thanks, I will look into this some time during the next few days. 🙂

**Pull request merged**
