### PR TITLE
WIP: Feature/time parser

### PR DESCRIPTION
**Pull request by jesperstarkar**
* **What kind of change does this PR introduce?** A safe-guard in parsing time-related values (not MOS-durations or MOS-time), but decimal-separated numbers for time (MediaTime, ReadTime) that _can_ come in as strings with odd decimal-separators in localised ENPS installations.

* **What is the current behavior?** If ENPS decides to send a number as the string `'14,3'` consuming clients will fail as this string i.e. through `parseFloat()` will en up as `14`. 

* **What is the new behavior (if this is a feature change)?** The odd case of the string `'14,3'` will be identified and parsed as `14.3`

* **Other information**: Work-in-progress, not ready to be merged.

### CODE REVIEW

**Comment by jesperstarkar** [comment]
@nytamin initial implementation - no opt-out for now

**Comment by jesperstarkar** [comment]
@nytamin should we filter to only fixify properties with "time" in the name?

So that another list of things like "1,2" can still live as strings?

**Comment by nytamin** [comment]
It's difficult to make that decision just by looking at the data (what about "duration", or "time" in another language).
I think that it is would be better to be able to add some more kind of opt out on a per-property basis.

**Comment by jesperstarkar** [comment]
The reasoning being this is metadata, meaning it is not mos-specific but ENPS-specific in this case.

**Pull request merged**
